# Generated by Django 3.2.13 on 2022-08-03 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0011_merge_20211020_1253'),
        ('summary', '0013_remove_dailyactiveuser'),
    ]

    operations = [
    ]
