# Generated by Django 2.2.24 on 2021-10-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20210716_1644'),
        ('reports', '0005_auto_20210726_2000'),
    ]

    operations = [
    ]
