# Generated by Django 3.2.13 on 2022-08-03 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_merge_20211020_1253'),
        ('reports', '0007_viewuserquizscores'),
    ]

    operations = [
    ]
