# Generated by Django 2.2.24 on 2021-10-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0040_auto_20210726_2000'),
        ('oppia', '0041_auto_20210816_1057'),
    ]

    operations = [
    ]
