# Generated by Django 2.2.24 on 2021-11-29 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0042_tracker_course_version'),
        ('oppia', '0042_merge_20211020_1253'),
    ]

    operations = [
    ]
