# Generated by Django 3.2.13 on 2022-08-03 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0043_merge_20211129_1245'),
        ('oppia', '0052_auto_20220726_0900'),
    ]

    operations = [
    ]
