# Generated by Django 3.2.15 on 2022-09-13 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0053_merge_20220803_0817'),
        ('oppia', '0054_cohort_criteria'),
    ]

    operations = [
    ]
