# Generated by Django 3.2.16 on 2022-11-04 16:02

from django.db import migrations, models
import oppia.models.badges


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0055_merge_0053_merge_20220803_0817_0054_cohort_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplate',
            name='image_file',
            field=models.ImageField(help_text='Use a .png image of 842px by 595px (at 72dpi), or use         equivalent dimension ratio for higher dpi', upload_to='certificate/templates', validators=[oppia.models.badges.CertificateTemplate.validate_image]),
        ),
    ]
